# 3-10 numpy中的比较和 Fancy Indexing

In [2]:
import numpy as np

In [3]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [4]:
# 索引一个值
x[3]

3

In [5]:
# 索引区间切片
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
# 切片步长
x[3:8:2]

array([3, 5, 7])

In [7]:
# 访问非等步长元素
[x[3], x[5], x[8]]

[3, 5, 8]

In [8]:
# 这就是 Fancy Indexing
ind = [3, 5, 8]

x[ind]

array([3, 5, 8])

In [10]:
ind = np.array([[0, 2],
                [1, 3]])

x[ind]

array([[0, 2],
       [1, 3]])

In [11]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
row = np.array([0, 1, 2])
col = np.array([1, 2, 3])
# (0, 1) (1, 2) (2, 3)

X[row, col]

array([ 1,  6, 11])

In [15]:
X[0, col]

array([1, 2, 3])

In [16]:
X[:2, col]

array([[1, 2, 3],
       [5, 6, 7]])

In [19]:
# 对索引为 0, 2, 3 的列感兴趣 
col = [True, False, True, True]

In [20]:
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 的比较运算

In [21]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [23]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [24]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [25]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [27]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [29]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [32]:
# 二维矩阵同样通用
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [33]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
np.sum(x <= 3)

4

In [35]:
np.count_nonzero(x <= 3)

4

In [36]:
# 是否存在 0 元素
np.any(x == 0)

True

In [37]:
# 是否有小于 0 的元素
np.any(x < 0)

False

In [38]:
np.all(x >= 0)

True

In [39]:
np.all(x > 0)

False

In [50]:
# 同样适用于矩阵
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
# 统计偶数的个数
np.sum(X % 2 == 0)

8

In [42]:
# 每行有多少个偶数
np.sum(X%2 == 0, axis=1)

array([2, 2, 2, 2])

In [44]:
# 列有多少个偶数
np.sum(X%2 == 0, axis=0)

array([4, 0, 4, 0])

In [53]:
np.any((X > 0), axis=1) # 感觉输出有问题？？？

array([ True,  True,  True,  True])

## 逻辑运算

In [52]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
np.sum((x > 3) & (x < 10))

6

In [55]:
np.sum((x % 2 == 0) | (x > 10))

11

In [57]:
np.sum(~(x == 0))

15

In [59]:
x[x < 5]

array([0, 1, 2, 3, 4])

In [60]:
x[x % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [61]:
# 最后一列可以被 3 整除
X[X[:, 3] % 3 == 0, :]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

### Pandas


Pandas 能够更方便的处理数据，进行预处理后，再转换为 Numpy，最后送入机器学习算法。